// GENERATED by the Blender addon (tools/blender/pc2_entity). A blueprint is an array of
// parts for spawnEntity (src/entity.js):
//   { mesh, pos, rot (degrees), scale, color?, uv?, parent? }
// A trailing `NAME.t = ...` is the TAG: the role the game looks an entity
// up by (loadStage in main.js buckets each stage by tag).
// `NAME.s` holds Blender-authored pose states; edit their part structure in Blender.
// One export per entity: blueprints nothing imports tree-shake out of the
// build and cost zero bytes.

export const CAPSULE = [
  { mesh: 'mesh_hemicylinder', scale: [1, 0.7, 1], color: 10 },
  { mesh: 'mesh_hemicylinder', rot: [0, 180, 0], color: 10, parent: 0 },
  { mesh: 'mesh_hemisphere', pos: [0, 0.35, 0], color: 10 },
  { mesh: 'mesh_hemisphere', pos: [0, -0.35, 0], rot: [180, 0, 0], color: 10 },
];
CAPSULE.t = 'enemy';

export const CUBE = [
  { mesh: 'mesh_cube', color: 8 },
];

export const HEMITORUS = [
  { mesh: 'mesh_torus', color: 8 },
];

export const CYLINDER = [
  { mesh: 'mesh_hemicylinder', color: 2 },
  { mesh: 'mesh_hemicylinder', rot: [0, 180, 0], color: 2, parent: 0 },
];

export const PLANE = [
  { mesh: 'mesh_plane', color: 1 },
];

export const SPHERE = [
  { mesh: 'mesh_hemisphere', color: 12 },
  { mesh: 'mesh_hemisphere', rot: [180, 0, 0], color: 12, parent: 0 },
];

export const SLICE = [
  { mesh: 'mesh_slice', color: 6 },
];

export const HEMISPHERE = [
  { mesh: 'mesh_hemisphere', color: 11 },
];

export const HORN = [
  { mesh: 'mesh_horn', color: 13 },
];

export const CUBE_TILED = [
  { mesh: 'mesh_cube', uv: { repeatU: 3, repeatV: 3 } },
];

export const UNICORN = [
  { pos: [-0.0038, 0.0736, -0.2249] },   // unicorn_rot
  { mesh: 'mesh_hemisphere', pos: [0, 0.5887, -0.0534], rot: [-5.1808, 0, 0], scale: [1.1587, 1.1587, 1.4822], color: 2, parent: 0 },
  { mesh: 'mesh_hemisphere', pos: [0, 0.5887, -0.0534], rot: [174.8192, 0, 0], scale: [1.1587, 1.1587, 1.4822], color: 2, parent: 0 },
  { mesh: 'mesh_horn', pos: [0, 1.4807, 0.2605], rot: [-13.5514, 180, 0], scale: [0.3181, 1, 0.3181], color: 5, parent: 0 },
  { mesh: 'mesh_hemisphere', pos: [0.0038, 0.4218, 0.8673], rot: [13.7142, 0, 0], color: 3, parent: 0 },
  { mesh: 'mesh_hemisphere', pos: [0.397, 0.7377, 1.0945], rot: [-71.6108, 0, 0], scale: [0.2824, 0.2824, 0.2824], color: 4, parent: 0 },
  { mesh: 'mesh_hemisphere', pos: [-0.3894, 0.7377, 1.0945], rot: [-71.6108, 0, 0], scale: [0.2824, 0.2824, 0.2824], color: 4, parent: 0 },
  { mesh: 'mesh_hemisphere', pos: [0.0038, 0.4065, 0.8636], rot: [13.7142, 0, 0], scale: [0.9016, 0.9016, 0.9016], color: 4, parent: 0 },
  { pos: [0.3525, 0.9101, -0.0662], parent: 0 },   // earL_rot
  { mesh: 'mesh_slice', pos: [0.356, 0.4952, -0.0712], rot: [85.4052, 2.7915, -36.0395], scale: [1.2273, 0.4701, 1.2273], color: 3, parent: 8 },
  { mesh: 'mesh_slice', pos: [0.2916, 0.4042, -0.04], rot: [85.4052, 2.7915, -36.0395], scale: [1, 0.383, 1], color: 4, parent: 8 },
  { pos: [-0.3449, 0.9101, -0.0662], parent: 0 },   // earR_rot
  { mesh: 'mesh_slice', pos: [-0.356, 0.4952, -0.0712], rot: [85.4052, -2.7915, 36.0395], scale: [1.2273, 0.4701, 1.2273], color: 3, parent: 11 },
  { mesh: 'mesh_slice', pos: [-0.2916, 0.4042, -0.04], rot: [85.4052, -2.7915, 36.0395], scale: [1, 0.383, 1], color: 4, parent: 11 },
  { pos: [0.4697, 0.8081, 0.3842], parent: 0 },   // eyeL_rot
  { mesh: 'mesh_hemisphere', rot: [-57.9413, 2.9744, 10.9815], scale: [0.4617, 0.5639, 0.4616], color: 4, parent: 14 },
  { mesh: 'mesh_hemisphere', pos: [0.4697, 0.8081, 0.3842], scale: [0.3676, 0.3676, 0.3676], color: 15, parent: 0 },
  { mesh: 'mesh_hemisphere', pos: [0.4697, 0.8081, 0.3842], rot: [180, 0, 0], scale: [0.3676, 0.3676, 0.3676], color: 15, parent: 0 },
  { mesh: 'mesh_hemisphere', pos: [0.5461, 0.8081, 0.5327], rot: [90, 22.582, 0], scale: [0.0583, 0.0308, 0.0953], color: 1, parent: 0 },
  { pos: [-0.4621, 0.8081, 0.3842], parent: 0 },   // eyeR_rot.
  { mesh: 'mesh_hemisphere', pos: [-0.0076, 0, 0], rot: [-57.9413, -2.9744, -10.9815], scale: [0.4617, 0.5639, 0.4616], color: 4, parent: 19 },
  { mesh: 'mesh_hemisphere', pos: [-0.3851, 0.8141, 0.5365], rot: [90, 22.582, 0], scale: [0.0583, 0.0308, 0.0953], color: 1, parent: 0 },
  { mesh: 'mesh_hemisphere', pos: [-0.4621, 0.8081, 0.3842], scale: [0.3676, 0.3676, 0.3676], color: 15, parent: 0 },
  { mesh: 'mesh_hemisphere', pos: [-0.4621, 0.8081, 0.3842], rot: [180, 0, 0], scale: [0.3676, 0.3676, 0.3676], color: 15, parent: 0 },
  { pos: [0.0038, 0.3281, 0.351], parent: 0 },   // jaw_rot
  { mesh: 'mesh_hemisphere', pos: [0, 0.0479, 0.3606], rot: [-12.4392, 0, 180], scale: [1, 1, 1.0432], color: 3, parent: 24 },
  { mesh: 'mesh_hemisphere', pos: [0, -0.0082, 0], scale: [0.8377, 0.8377, 0.8377], color: 4, parent: 25 },
];
UNICORN.s = [
  [0b111111111111111111111111111, []],   // calm
  [0b111111111111111111111111111, [[0, [-0.0038, 0.1249, -0.2249], [-14.294, -14.6908, -15.8355], [1.3202, 1.3202, 1.3202]], [8, 0, [-5.3277, 3.6579, -17.6377], 0], [11, 0, [6.8878, -10.2436, 33.888], 0], [14, 0, [43.4012, 6.9931, -18.4664], 0], [19, 0, [43.4954, -7.0483, 23.0875], 0], [24, 0, [36.7246, -2.6221, 6.4404], 0]]],   // spooked
];
UNICORN.t = 'player';
// State part indices follow the blueprint above; reordering parts must remap them.


export const MOLE = [
  { mesh: 'mesh_hemicylinder', pos: [0, 0.5, 0], color: 4 },
  { mesh: 'mesh_hemicylinder', rot: [0, 180, 0], color: 4, parent: 0 },
  { pos: [0, 0.5, -0.5101], scale: [1, 1, 1.0753], parent: 0 },   // mouth_rot
  { mesh: 'mesh_hemisphere', pos: [0, 0, 0.5101], rot: [0, 180, 0], color: 4, parent: 2 },
  { pos: [0, 0.2324, -0.4266], rot: [0, 180, 0], parent: 3 },   // nose_rot
  { mesh: 'mesh_hemisphere', pos: [0, -0.1236, 0.051], rot: [-19.4512, 180, 0], scale: [0.2688, 0.2688, 0.2475], color: 5, parent: 4 },
  { mesh: 'mesh_hemisphere', rot: [180, 0, 0], color: 5, parent: 5 },
  { pos: [-0.2, 0.175, -0.3582], rot: [-90, 0, 0], scale: [0.2093, 0.1946, 0.2093], parent: 3 },   // @EYE_SIMPLE
  { mesh: 'mesh_hemisphere', color: 1, parent: 7 },
  { parent: 7 },   // pivot_eyelid
  { mesh: 'mesh_hemisphere', rot: [120, 0, 0], scale: [1.2296, 1.2296, 1.2296], color: 5, parent: 9 },
  { parent: 7 },   // pivot_pupil
  { mesh: 'mesh_hemisphere', pos: [0, 0.3854, 0], scale: [0.4585, 0.3332, 0.4585], color: 15, parent: 11 },
  { pos: [0.2, 0.175, -0.3582], rot: [-90, 0, 0], scale: [0.2093, 0.1946, 0.2093], parent: 3 },   // @EYE_SIMPLE
  { mesh: 'mesh_hemisphere', color: 1, parent: 13 },
  { parent: 13 },   // pivot_eyelid
  { mesh: 'mesh_hemisphere', rot: [120, 0, 0], scale: [1.2296, 1.2296, 1.2296], color: 5, parent: 15 },
  { parent: 13 },   // pivot_pupil
  { mesh: 'mesh_hemisphere', pos: [0, 0.3854, 0], scale: [0.4585, 0.3332, 0.4585], color: 15, parent: 17 },
  { mesh: 'mesh_cube', pos: [0.1195, 0.9192, 0.4955], rot: [90, -156.7027, 0], scale: [0.1791, 0.0232, 0.1858], color: 1 },
  { mesh: 'mesh_cube', pos: [-0.1236, 0.9192, 0.4937], rot: [90, 156.7027, 0], scale: [0.1791, 0.0232, 0.1858], color: 1 },
  { mesh: 'mesh_hemicylinder', pos: [0, 0.4936, 0], scale: [0.8, 0.035, 0.8], color: 5, parent: 0 },
  { mesh: 'mesh_hemicylinder', rot: [0, 180, 0], color: 5, parent: 21 },
  { mesh: 'mesh_hemisphere', pos: [0.4391, 1.4477, 0.0292], rot: [-92.664, 14.7669, -35.3453], scale: [0.3015, 0.3015, 0.4161], color: 5 },
  { mesh: 'mesh_hemisphere', pos: [-0.4391, 1.4477, 0.0292], rot: [-92.664, -14.7669, 35.3453], scale: [0.3015, 0.3015, 0.4161], color: 5 },
];
MOLE.t = 'enemy';


export const CARNY = [
  { mesh: 'mesh_hemicylinder', pos: [0, 1, 0], color: 4 },
  { mesh: 'mesh_hemicylinder', rot: [0, 180, 0], color: 4, parent: 0 },
  { mesh: 'mesh_hemisphere', pos: [0, -0.5, 0], rot: [0, 0, 180], scale: [1, 0.976, 1], color: 4, parent: 0 },
  { pos: [0, 0.5, -0.5101], parent: 0 },   // mouth_rot
  { mesh: 'mesh_hemisphere', pos: [0, 0, 0.5101], rot: [0, 180, 0], color: 4, parent: 3 },
  { pos: [0, 0.2324, -0.4266], rot: [0, 180, 0], parent: 4 },   // nose_rot
  { mesh: 'mesh_hemisphere', pos: [0, -0.1462, 0.1149], rot: [-19.4512, 180, 0], scale: [0.2688, 0.2688, 0.4239], color: 5, parent: 5 },
  { mesh: 'mesh_hemisphere', rot: [180, 0, 0], color: 5, parent: 6 },
  { mesh: 'mesh_hemicylinder', pos: [0, -0.1223, -0.494], rot: [90, 0, 0], scale: [-0.9804, -0.0698, -0.3741], color: 15, parent: 4 },
  { pos: [0.2, 0.175, 0.9101], rot: [90, 0, 180], scale: [0.215, 0.215, 0.215], parent: 3 },   // @EYE_COMPLEX
  { parent: 9 },   // pivot_eyelidUpper
  { mesh: 'mesh_hemisphere', rot: [120, 0, 0], scale: [1.2296, 1.2296, 1.2296], color: 5, parent: 10 },
  { parent: 9 },   // pivot_pupil
  { mesh: 'mesh_hemisphere', pos: [0, 0.3854, 0], scale: [0.4, 0.3332, 0.4], color: 10, parent: 12 },
  { parent: 9 },   // pivot_eyelidLower
  { mesh: 'mesh_hemisphere', rot: [-160, 0, 0], scale: [1.2296, 1.2296, 1.2296], color: 5, parent: 14 },
  { mesh: 'mesh_hemisphere', color: 1, parent: 9 },
  { pos: [-0.2, 0.175, 0.9101], rot: [90, 0, 180], scale: [0.215, 0.215, 0.215], parent: 3 },   // @EYE_COMPLEX
  { parent: 17 },   // pivot_eyelidUpper
  { mesh: 'mesh_hemisphere', rot: [120, 0, 0], scale: [1.2296, 1.2296, 1.2296], color: 5, parent: 18 },
  { parent: 17 },   // pivot_pupil
  { mesh: 'mesh_hemisphere', pos: [0, 0.3854, 0], scale: [0.4, 0.3332, 0.4], color: 10, parent: 20 },
  { parent: 17 },   // pivot_eyelidLower
  { mesh: 'mesh_hemisphere', rot: [-160, 0, 0], scale: [1.2296, 1.2296, 1.2296], color: 5, parent: 22 },
  { mesh: 'mesh_hemisphere', color: 1, parent: 17 },
  { mesh: 'mesh_hemicylinder', pos: [0, 0.4936, 0], scale: [0.8, 0.035, 0.8], color: 5, parent: 0 },
  { mesh: 'mesh_hemicylinder', rot: [0, 180, 0], color: 5, parent: 25 },
];
CARNY.t = 'enemy';

export const COLOR_WHEEL = [
  {},   // wheel_xform
  { mesh: 'mesh_hemicylinder', pos: [0, 1.25, -0.1504], rot: [90, 0, 180], scale: [0.5296, 0.0386, 0.5296], color: 15, parent: 0 },   // cylinder
  { mesh: 'mesh_hemicylinder', pos: [0, 1.25, -0.1504], rot: [90, 0, 0], scale: [0.5296, 0.0386, 0.5296], color: 15, parent: 0 },   // cylinder.back
  { mesh: 'mesh_hemicylinder', rot: [0.0029, 0, 180], scale: [0.7913, 1.5789, 0.7913], color: 3, parent: 2 },   // cylinder.back
  { pos: [0.1053, 1.3026, -0.1647], rot: [-90, -0.0002, -16.3549], scale: [0.125, 0.125, 0.125], parent: 0 },   // @EYE_SIMPLE
  { mesh: 'mesh_hemisphere', color: 1, parent: 4 },
  { parent: 4 },   // pivot_eyelid
  { mesh: 'mesh_hemisphere', rot: [120, 0, 0], scale: [1.2296, 1.2296, 1.2296], color: 5, parent: 6 },
  { parent: 4 },   // pivot_pupil
  { mesh: 'mesh_hemisphere', pos: [0, 0.3854, 0], scale: [0.4585, 0.3332, 0.4585], color: 15, parent: 8 },
  { pos: [-0.0947, 1.3067, -0.1647], rot: [-89.9973, -0.0002, 13.4888], scale: [0.125, 0.125, 0.125], parent: 0 },   // @EYE_SIMPLE
  { mesh: 'mesh_hemisphere', color: 1, parent: 10 },
  { parent: 10 },   // pivot_eyelid
  { mesh: 'mesh_hemisphere', rot: [120, 0, 0], scale: [1.2296, 1.2296, 1.2296], color: 5, parent: 12 },
  { parent: 10 },   // pivot_pupil
  { mesh: 'mesh_hemisphere', pos: [0, 0.3854, 0], scale: [0.4585, 0.3332, 0.4585], color: 15, parent: 14 },
  { mesh: 'mesh_slice', pos: [0, 2.2974, -0.101], rot: [-90, 0, 0], scale: [0.6795, 0.1931, 0.5997], color: 1, parent: 0 },   // shows_color
  { pos: [0, 1.25, 0], parent: 0 },   // wheel_rot
  { mesh: 'mesh_hemicylinder', rot: [-90, 0, 0], scale: [2, 0.15, 2], color: 15, parent: 17 },
  { mesh: 'mesh_hemicylinder', rot: [0, 180, 0], color: 15, parent: 18 },
  { mesh: 'mesh_slice', pos: [0, 0.4401, -0.0238], rot: [0, 180, 0], scale: [0.8912, 6.6667, 0.8912], color: 6, parent: 19 },
  { mesh: 'mesh_slice', pos: [-0.0168, 0.4401, -0.0168], rot: [0, -135, 0], scale: [0.8912, 6.6667, 0.8912], color: 1, parent: 19 },
  { mesh: 'mesh_slice', pos: [-0.0238, 0.4401, 0], rot: [0, -90, 0], scale: [0.8912, 6.6667, 0.8912], color: 14, parent: 19 },
  { mesh: 'mesh_slice', pos: [-0.0168, 0.4401, 0.0168], rot: [0, -45, 0], scale: [0.8912, 6.6667, 0.8912], color: 12, parent: 19 },
  { mesh: 'mesh_slice', pos: [0, 0.4401, 0.0238], scale: [0.8912, 6.6667, 0.8912], color: 10, parent: 19 },
  { mesh: 'mesh_slice', pos: [0.0168, 0.4401, 0.0168], rot: [0, 45, 0], scale: [0.8912, 6.6667, 0.8912], color: 8, parent: 19 },
  { mesh: 'mesh_slice', pos: [0.0238, 0.4401, 0], rot: [0, 90, 0], scale: [0.8912, 6.6667, 0.8912], color: 2, parent: 19 },
  { mesh: 'mesh_slice', pos: [0.0168, 0.4401, -0.0168], rot: [0, 135, 0], scale: [0.8912, 6.6667, 0.8912], color: 4, parent: 19 },
  { mesh: 'mesh_hemicylinder', pos: [0, 1.25, -0.1504], rot: [-90.0004, 0, 0], scale: [0.4191, 0.061, 0.4191], color: 3, parent: 0 },   // cylinder
  { mesh: 'mesh_hemisphere', pos: [0, 1.1537, -0.1504], rot: [-6.3021, 0, 0], scale: [0.2918, 0.2918, 0.5157], color: 4 },
  { mesh: 'mesh_hemisphere', pos: [0, 1.1595, -0.1885], rot: [21.1523, 0, 180], scale: [0.2067, 0.2067, 0.3653], color: 5 },
];
COLOR_WHEEL.s = [
  [0b1111111111111111111111111111111, [[4, [0.1053, 1.3026, -0.1634], [-90, 0, 0], 0], [6, 0, [-120, 0, 0], 0], [10, [-0.0947, 1.3067, -0.1634], [-89.9986, -0.0007, -0.0007], 0], [12, 0, [-120, 0, 0], 0]]],   // BLINK
];
COLOR_WHEEL.t = 'bonus';

export const RAINBOWFLATTER = [
  { mesh: 'mesh_hemicylinder', rot: [-90, 0, 0], scale: [20, 0.5, 20], color: 6 },
  { mesh: 'mesh_hemicylinder', pos: [0, 0, -0.5], rot: [-90, 0, 0], scale: [17.5, 0.5, 17.5], color: 4 },
  { mesh: 'mesh_hemicylinder', pos: [0, 0, -1], rot: [-90, 0, 0], scale: [15, 0.5, 15], color: 2 },
  { mesh: 'mesh_hemicylinder', pos: [0, 0, -1.5], rot: [-90, 0, 0], scale: [12.5, 0.5, 12.5], color: 8 },
  { mesh: 'mesh_hemicylinder', pos: [0, 0, -2], rot: [-90, 0, 0], scale: [10, 0.5, 10], color: 10 },
  { mesh: 'mesh_hemicylinder', pos: [0, 0, -2.5], rot: [-90, 0, 0], scale: [7.5, 0.5, 7.5], color: 12 },
  { mesh: 'mesh_hemicylinder', pos: [0, 0, -3], rot: [-90, 0, 0], scale: [5, 0.5, 5], color: 14 },
];

export const RAINBOW = [
  { mesh: 'mesh_torus', rot: [-90, 0, 0], scale: [20, 10, 20], color: 6 },
  { mesh: 'mesh_torus', pos: [0, 0, -0.5], rot: [-90, 0, 0], scale: [17.5, 10, 17.5], color: 4 },
  { mesh: 'mesh_torus', pos: [0, 0, -1], rot: [-90, 0, 0], scale: [15, 10, 15], color: 2 },
  { mesh: 'mesh_torus', pos: [0, 0, -1.5], rot: [-90, 0, 0], scale: [12.5, 10, 12.5], color: 8 },
  { mesh: 'mesh_torus', pos: [0, 0, -2], rot: [-90, 0, 0], scale: [10, 10, 10], color: 10 },
  { mesh: 'mesh_torus', pos: [0, 0, -2], rot: [-90, 0, 0], scale: [7.5, 10, 7.5], color: 12 },
  { mesh: 'mesh_torus', pos: [0, 0, -2.5], rot: [-90, 0, 0], scale: [5, 10, 5], color: 14 },
];

export const EYE_SIMPLE = [
  { mesh: 'mesh_hemisphere', color: 1 },
  {},   // pivot_eyelid
  { mesh: 'mesh_hemisphere', rot: [120, 0, 0], scale: [1.2296, 1.2296, 1.2296], color: 5, parent: 1 },
  {},   // pivot_pupil
  { mesh: 'mesh_hemisphere', pos: [0, 0.3854, 0], scale: [0.4585, 0.3332, 0.4585], color: 15, parent: 3 },
];
EYE_SIMPLE.s = [
  [0b11111, [[1, 0, [-120, 0, 0], 0]]],   // closed
];

export const EYE_COMPLEX = [
  {},   // pivot_eyelidUpper
  { mesh: 'mesh_hemisphere', rot: [120, 0, 0], scale: [1.2296, 1.2296, 1.2296], color: 5, parent: 0 },
  {},   // pivot_pupil
  { mesh: 'mesh_hemisphere', pos: [0, 0.3854, 0], scale: [0.4, 0.3332, 0.4], color: 10, parent: 2 },
  {},   // pivot_eyelidLower
  { mesh: 'mesh_hemisphere', rot: [-160, 0, 0], scale: [1.2296, 1.2296, 1.2296], color: 5, parent: 4 },
  { mesh: 'mesh_hemisphere', color: 1 },
];
EYE_COMPLEX.s = [
  [0b1111111, [[0, 0, [-45, 0, 0], 0], [4, 0, [55, 0, 0], 0]]],   // closed
  [0b1111111, [[0, 0, [-15, 0, 0], 0], [3, 0, 0, [0.315, 0.2624, 0.315]], [4, 0, [65, 0, 0], 0]]],   // angry
  [0b1111111, [[0, 0, [30, 0, 0], 0], [3, 0, 0, [0.58, 0.4831, 0.58]], [4, 0, [-10, 0, 0], 0]]],   // surprised
];

export const STAR = [
  { mesh: 'mesh_hemisphere', pos: [0, -0.0137, 0], scale: [0.3556, 0.1079, 0.3556], color: 3 },
  { mesh: 'mesh_slice', pos: [0, 0, -0.5452], scale: [1, 0.3932, 1], color: 4 },
  { mesh: 'mesh_slice', pos: [0.5452, 0, 0], rot: [0, -90, 0], scale: [1, 0.3932, 1], color: 4 },
  { mesh: 'mesh_slice', pos: [-0.5452, 0, 0], rot: [0, 90, 0], scale: [1, 0.3932, 1], color: 4 },
  { mesh: 'mesh_slice', pos: [0, 0, 0.5452], rot: [0, 180, 0], scale: [1, 0.3932, 1], color: 4 },
];

export const TARGET_1 = [
  { mesh: 'mesh_hemisphere', color: 1 },   // sphere.target
  { mesh: 'mesh_hemisphere', rot: [180, 0, 0], color: 1, parent: 0 },   // sphere.lower
];
TARGET_1.t = 'target';

export const WATERGUN = [
  { pos: [0, 0.2041, -0.3387] },   // watergun_pivot
  { mesh: 'mesh_hemisphere', pos: [0, 0, 0.0137], rot: [-90, 0, 0], scale: [0.2721, 0.2889, 0.2721], color: 5, parent: 0 },
  { mesh: 'mesh_hemicylinder', pos: [0, 0, 0.1469], rot: [-90, 0, 0], scale: [0.236, 0.275, 0.251], color: 10, parent: 0 },   // cylinder
  { mesh: 'mesh_hemicylinder', pos: [0, 0, 0.1675], rot: [-90, 0, 180], scale: [0.275, 0.3135, 0.275], color: 5, parent: 0 },   // cylinder.back
  { mesh: 'mesh_hemicylinder', pos: [0, 0, 0.2963], rot: [-90, 0, 0], scale: [0.275, 0.0556, 0.275], color: 5, parent: 0 },   // cylinder.back
  { mesh: 'mesh_hemicylinder', pos: [0, 0.0409, 0.4267], rot: [-90, 0, 0], scale: [0.1091, 0.2158, 0.1091], color: 4, parent: 0 },   // cylinder
  { mesh: 'mesh_hemicylinder', pos: [0, 0.0409, 0.4267], rot: [-90, 0, 180], scale: [0.1091, 0.2158, 0.1091], color: 4, parent: 0 },   // cylinder.back
  { mesh: 'mesh_torus', pos: [-0.1112, -0.026, 0.1583], rot: [-101.2202, -77.7884, 90.0829], scale: [0.3472, 0.3512, 0.3491], color: 10, parent: 0 },
  { mesh: 'mesh_torus', pos: [0.1112, -0.026, 0.1583], rot: [-101.2202, 77.7884, -90.0829], scale: [0.3472, 0.3512, 0.3491], color: 10, parent: 0 },
  { mesh: 'mesh_slice', pos: [-0.0641, 0, -0.0566], rot: [-135, 0, 90], scale: [0.514, 0.514, 0.514], color: 4, parent: 0 },
  { mesh: 'mesh_hemicylinder', pos: [0, -0.0625, 0.5], rot: [0, -135, 90], scale: [0.1801, 0.652, 0.1801], color: 5, parent: 9 },   // handle_L
  { mesh: 'mesh_hemicylinder', rot: [0, 180, 0], color: 5, parent: 10 },   // cylinder.back
  { mesh: 'mesh_slice', pos: [0.0641, 0, -0.0566], rot: [-135, 0, -90], scale: [0.514, 0.514, 0.514], color: 4, parent: 0 },
  { mesh: 'mesh_hemicylinder', pos: [0, -0.0625, 0.5], rot: [0, 135, -90], scale: [0.1801, 0.652, 0.1801], color: 5, parent: 12 },   // handle_R
  { mesh: 'mesh_hemicylinder', rot: [0, 180, 0], color: 5, parent: 13 },   // cylinder.back
  { pos: [0, 0.0409, 0.6529], parent: 0 },   // watergun_aim
  { pos: [0, 0.0409, 0.4596], parent: 0 },   // ScaleSpout
  { mesh: 'mesh_hemisphere', pos: [0, 0, 0.2131], rot: [-90, 0, 0], scale: [0.2001, 0.4178, 0.2001], color: 5, parent: 16 },
];

export const ARROW = [
  {},   // arrow_point
  { mesh: 'mesh_cube', scale: [0.5, 0.1, 1], color: 7, parent: 0 },
  { mesh: 'mesh_slice', pos: [0, 0, 1.2036], rot: [0, 180, 0], scale: [5.7658, 8.6488, 1.8124], color: 7, parent: 1 },
];

export const TIMER = [
  { mesh: 'mesh_cube', scale: [2, 0.1, 1.28], color: 15 },
  { mesh: 'mesh_cube', pos: [0, 0.1, 0.6], rot: [45, 0, 0], scale: [2.16, 0.175, 0.175], color: 7 },
  { mesh: 'mesh_cube', pos: [0, 0.1, -0.6], rot: [45, 0, 0], scale: [2.16, 0.175, 0.175], color: 7 },
  { mesh: 'mesh_cube', pos: [-0.95, 0.1, 0], rot: [45, -90, 0], scale: [1.0752, 0.175, 0.175], color: 7 },
  { mesh: 'mesh_cube', pos: [0.95, 0.1, 0], rot: [45, -90, 0], scale: [1.0752, 0.175, 0.175], color: 7 },
];

// A marker: one mesh-less part, so it draws nothing. Place it in a stage to
// name a POSITION (and facing) the game looks up -- STAGE_1's CARNY slides to
// the MARK placement when the clock runs out. main.js removes it from the
// object list on load so it can neither be hit nor block a shot.
export const MARK = [
  { },   // mark
];

export const MALLET = [
  {},
  { mesh: 'mesh_hemicylinder', pos: [0, 0, 0.3], rot: [-90, 0, 0], scale: [0.2, 1, 0.2], color: 4, parent: 0 },   // cylinder
  { mesh: 'mesh_hemicylinder', pos: [0, -1, 0], rot: [90, -90, 0], scale: [5, 5, 1], color: 4, parent: 1 },   // cylinder
  { mesh: 'mesh_hemicylinder', rot: [0, 180, 0], color: 4, parent: 2 },   // cylinder.back
  { mesh: 'mesh_hemicylinder', pos: [-2.5, -1, 0], rot: [90, -90, 0], scale: [5.6484, 0.6413, 1.1297], color: 5, parent: 1 },   // cylinder
  { mesh: 'mesh_hemicylinder', rot: [0, 180, 0], color: 5, parent: 4 },   // cylinder.back
  { mesh: 'mesh_hemicylinder', pos: [2.5, -1, 0], rot: [90, 90, 0], scale: [5.6484, 0.6413, 1.1297], color: 5, parent: 1 },   // cylinder
  { mesh: 'mesh_hemicylinder', rot: [0, 180, 0], color: 5, parent: 6 },   // cylinder.back
  { mesh: 'mesh_hemicylinder', rot: [0, 180, 0], color: 4, parent: 1 },   // cylinder.back
];

export const WHACKA = [
  { mesh: 'mesh_cube', pos: [0, -1.05, 0], scale: [2.1, 2.1, 2.1], color: 5 },
  { mesh: 'mesh_cube', pos: [0, -0.7067, 0], scale: [1.47, 1.47, 1.47], color: 15 },
  { mesh: 'mesh_torus', scale: [2.1507, 1, 2.1507], color: 9 },
  { mesh: 'mesh_torus', rot: [0, 180, 0], color: 9, parent: 2 },
];

export const X = [
  { mesh: 'mesh_slice', pos: [0.0835, 0, -0.0835], rot: [0, -45, 0], scale: [0.5484, 1, 1], color: 6 },
  { mesh: 'mesh_slice', pos: [-0.0835, 0, -0.0835], rot: [0, 45, 0], scale: [0.5484, 1, 1], color: 6 },
  { mesh: 'mesh_slice', pos: [-0.0835, 0, 0.0835], rot: [0, 135, 0], scale: [0.5484, 1, 1], color: 6 },
  { mesh: 'mesh_slice', pos: [0.0835, 0, 0.0835], rot: [0, -135, 0], scale: [0.5484, 1, 1], color: 6 },
];
